import jsPDF from "jspdf";

const checkPage = (doc, y) => {
    if (y > 270) {
        doc.addPage();
        return 20;
    }

    return y;
};

const addBulletList = (doc, items, y) => {

    if (!Array.isArray(items)) {
        return y;
    }

    items.forEach((item) => {

        y = checkPage(doc, y);

        const lines = doc.splitTextToSize(
            `• ${String(item)}`,
            160
        );

        doc.text(lines, 25, y);

        y += lines.length * 7 + 2;
    });

    return y;
};

export const downloadReport = (aiResult) => {

    if (!aiResult) {
        alert("No AI analysis available.");
        return;
    }

    const doc = new jsPDF();

    const parsed = aiResult.parsedResume || {};

    // Support both possible response structures
    const skills =
        aiResult.skills ||
        parsed.skills?.flatMap(category =>
            Array.isArray(category.items)
                ? category.items
                : []
        ) ||
        [];

    const strengths =
        aiResult.strengths ||
        parsed.strengths ||
        [];

    const weaknesses =
        aiResult.weaknesses ||
        parsed.weaknesses ||
        [];

    const missingSkills =
        aiResult.missingSkills ||
        parsed.missingSkills ||
        [];

    const suggestions =
        aiResult.suggestions ||
        parsed.suggestions ||
        [];

    const careerRecommendation =
        aiResult.careerRecommendation ||
        parsed.careerRecommendation ||
        "No career recommendation available.";

    // --------------------------------
    // HEADER
    // --------------------------------

    doc.setFontSize(22);
    doc.setTextColor(124, 58, 237);
    doc.text("FutureTwin AI", 20, 20);

    doc.setTextColor(0, 0, 0);

    doc.setFontSize(16);
    doc.text("Resume Analysis Report", 20, 30);

    doc.line(20, 35, 190, 35);

    // --------------------------------
    // SCORES
    // --------------------------------

    doc.setFontSize(12);

    doc.text(
        `Resume Score: ${aiResult.resumeScore ?? "--"}%`,
        20,
        50
    );

    doc.text(
        `ATS Score: ${aiResult.atsScore ?? "--"}%`,
        20,
        60
    );

    doc.text(
        `Recruiter Score: ${aiResult.recruiterScore ?? "--"}%`,
        20,
        70
    );

    doc.text(
        `Interview Readiness: ${aiResult.interviewReadiness ?? "--"}%`,
        20,
        80
    );

    // --------------------------------
    // VERDICT
    // --------------------------------

    doc.setFontSize(16);
    doc.text("Recruiter Verdict", 20, 100);

    doc.setFontSize(12);

    const verdict = aiResult.verdict || "No verdict available.";

    const verdictLines = doc.splitTextToSize(
        String(verdict),
        160
    );

    doc.text(verdictLines, 20, 110);

    let y = 110 + verdictLines.length * 7 + 10;

    // --------------------------------
    // DETECTED SKILLS
    // --------------------------------

    y = checkPage(doc, y);

    doc.setFontSize(16);
    doc.text("Detected Skills", 20, y);

    y += 10;

    doc.setFontSize(12);

    y = addBulletList(doc, skills, y);

    // --------------------------------
    // STRENGTHS
    // --------------------------------

    y += 5;
    y = checkPage(doc, y);

    doc.setFontSize(16);
    doc.text("Strengths", 20, y);

    y += 10;

    doc.setFontSize(12);

    y = addBulletList(doc, strengths, y);

    // --------------------------------
    // WEAKNESSES
    // --------------------------------

    y += 5;
    y = checkPage(doc, y);

    doc.setFontSize(16);
    doc.text("Weaknesses", 20, y);

    y += 10;

    doc.setFontSize(12);

    y = addBulletList(doc, weaknesses, y);

    // --------------------------------
    // MISSING SKILLS
    // --------------------------------

    y += 5;
    y = checkPage(doc, y);

    doc.setFontSize(16);
    doc.text("Missing Skills", 20, y);

    y += 10;

    doc.setFontSize(12);

    y = addBulletList(doc, missingSkills, y);

    // --------------------------------
    // AI SUGGESTIONS
    // --------------------------------

    y += 5;
    y = checkPage(doc, y);

    doc.setFontSize(16);
    doc.text("AI Suggestions", 20, y);

    y += 10;

    doc.setFontSize(12);

    y = addBulletList(doc, suggestions, y);

    // --------------------------------
    // CAREER RECOMMENDATION
    // --------------------------------

    y += 5;
    y = checkPage(doc, y);

    doc.setFontSize(16);
    doc.text("Career Recommendation", 20, y);

    y += 10;

    doc.setFontSize(12);

    const careerText = doc.splitTextToSize(
        String(careerRecommendation),
        160
    );

    doc.text(careerText, 25, y);

    y += careerText.length * 7 + 15;

    y = checkPage(doc, y);

    // --------------------------------
    // FOOTER
    // --------------------------------

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
        `Generated by FutureTwin AI • ${new Date().toLocaleDateString()}`,
        20,
        y
    );

    // --------------------------------
    // DOWNLOAD
    // --------------------------------

    doc.save("FutureTwin_AI_Resume_Report.pdf");
};