import { jsPDF } from "jspdf";

export function generateJobMatchPDF(result) {

    const doc = new jsPDF();

    let y = 20;

    const today = new Date().toLocaleDateString();

    const checkPageBreak = (space = 20) => {

        if (y + space > 280) {

            doc.addPage();

            y = 20;

        }

    };

    // ----------------------------
    // Title
    // ----------------------------

    doc.setFontSize(22);

    doc.setTextColor(120, 70, 255);

    doc.text("FutureTwin AI Report", 20, y);

    y += 15;

    doc.setDrawColor(120, 70, 255);

    doc.line(20, y, 190, y);

    y += 8;

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(`Generated on: ${today}`, 20, y);

    y += 15;

    // ----------------------------
    // Overall Verdict
    // ----------------------------

    doc.setFontSize(16);

    doc.setTextColor(0);

    doc.text("Overall Verdict", 20, y);

    y += 8;

    doc.setFontSize(12);

    doc.text(result.overallVerdict, 20, y);

    y += 15;

    // ----------------------------
    // Match Score
    // ----------------------------

    doc.setFontSize(16);

    doc.text("Match Score", 20, y);

    y += 8;

    doc.setFontSize(24);

    doc.text(`${result.matchScore}%`, 20, y);

    y += 15;

    // ----------------------------
    // Hiring Chance
    // ----------------------------

    doc.setFontSize(16);

    doc.text("Hiring Chance", 20, y);

    y += 8;

    if (result.hiringChance === "High")

        doc.setTextColor(0, 170, 0);

    else if (result.hiringChance === "Medium")

        doc.setTextColor(255, 140, 0);

    else

        doc.setTextColor(220, 0, 0);

    doc.setFontSize(12);

    doc.text(result.hiringChance, 20, y);

    doc.setTextColor(0);

    y += 15;

    doc.line(20, y, 190, y);

    y += 10;

    // ----------------------------
    // Matching Skills
    // ----------------------------

    doc.setFontSize(16);

    doc.text("Matching Skills", 20, y);

    y += 10;

    doc.setFontSize(12);

    result.matchingSkills.forEach(skill => {

        checkPageBreak(10);

        doc.text(`• ${skill}`, 25, y);

        y += 7;

    });

    y += 8;

    doc.line(20, y, 190, y);

    y += 10;

    // ----------------------------
    // Missing Skills
    // ----------------------------

    doc.setFontSize(16);

    doc.text("Missing Skills", 20, y);

    y += 10;

    doc.setFontSize(12);

    result.missingSkills.forEach(skill => {

        checkPageBreak(10);

        doc.text(`• ${skill}`, 25, y);

        y += 7;

    });

    y += 8;

    doc.line(20, y, 190, y);

    y += 10;

    // ----------------------------
    // Suggestions
    // ----------------------------

    doc.setFontSize(16);

    doc.text("Suggestions", 20, y);

    y += 10;

    doc.setFontSize(12);

    result.suggestions.forEach(item => {

        checkPageBreak(10);

        doc.text(`• ${item}`, 25, y);

        y += 7;

    });

    y += 15;

    // ----------------------------
    // Footer
    // ----------------------------

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(

        "Generated by FutureTwin AI",

        20,

        y

    );

    y += 6;

    doc.text(

        "AI Powered Career Guidance Platform",

        20,

        y

    );

    doc.save("FutureTwin_AI_Report.pdf");

}